version: "3.8"

services:
  db:
    image: postgres:14.4-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      KTOR_DATASOURCE_URL: jdbc:postgresql://db:5432/app
      KTOR_DATASOURCE_USERNAME: user
      KTOR_DATASOURCE_PASSWORD: pass
      SERVER_HOST: 0.0.0.0